[supabase]
url = "https://bxdeviypbktnlwkhccgp.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4ZGV2aXlwYmt0bmx3a2hjY2dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNTcyNTMsImV4cCI6MjA2NzkzMzI1M30.fxoZQJFMhmouUjkr-0Cxi3U-l1gJ4UwoxKvxaJ-hafE"
OPENAI_API_KEY = "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"